POST http://localhost:3003/api/blogs/66cc293dd905e1760ab6e9aa/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBoaWxsaXBGb3JMb2dpbiIsImlkIjoiNjZjNWI4YjYyZmQ4OWRmZjRlNWIyYTU2IiwiaWF0IjoxNzI0NjU1NzA0fQ.vrgNVK9aTG0ofqp_sZSqa5uzhLrQtboUFwWjS-Fq8tM

{
  "content": "comment content TEST"
}