POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBoaWxsaXBGb3JMb2dpbiIsImlkIjoiNjZjNWI4YjYyZmQ4OWRmZjRlNWIyYTU2IiwiaWF0IjoxNzI0NjExNTMyfQ.Dh9-ePFdufo2eukcUfKEVZtd_RFYKE8ADqI5m5dSgXg

{
  "title": "for Comments testing",
  "author": "PhillipForLogin",
  "url": "https://websiteofwonders5.de",
  "likes": 0
}
###
# this works not anymore because we need a web token now, ( now the returned object has a user and the user will have the blog in the blogs array)
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "another last blog post",
  "author": "bananenphil-4",
  "url": "https://websiteofwonders3.de",
  "likes": 15,
  "userId": "66964c313c399a7a0a37b7d6"
}
###
#does not work anymore because we need the userId
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "my third blog post",
  "author": "bananenphil",
  "url": "https://websiteofwonders2.de",
  "likes": 2
}